channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.11
  - biopython=1.81
  - pandas=1.5.3
  - nextflow=22.10.6.5843
  - jupyter=1.0.0
  - r-irkernel=1.3.2
  - r-tidyverse=2.0.0
